-- 迭代 9: MySQL DATETIME 升级到 DATETIME(6)（微秒精度）
-- 联调报告遗留 #4：同秒内编辑评论，updated_at 与 created_at 显示相同
-- 影响范围：所有 datetime 字段
-- 部署前在生产 MySQL 上执行
-- 注意：
--   1. MySQL 5.6.4+ 支持 DATETIME(6)
--   2. 升级不会丢失数据
--   3. 已有数据保留秒级精度（小数位补 0）

USE zlearn_db;

-- users 表
ALTER TABLE users
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY COLUMN updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

-- plans 表
ALTER TABLE plans
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY COLUMN updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

-- stages 表
ALTER TABLE stages
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY COLUMN updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

-- tasks 表
ALTER TABLE tasks
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY COLUMN completed_at DATETIME(6) NULL;

-- comments 表（重点：updated_at 在 ON UPDATE 时也需微秒精度）
ALTER TABLE comments
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY COLUMN updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

-- point_logs 表
ALTER TABLE point_logs
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6);

-- reminders 表
ALTER TABLE reminders
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6);

-- reports 表
ALTER TABLE reports
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6);

-- token_blacklist 表
ALTER TABLE token_blacklist
    MODIFY COLUMN revoked_at DATETIME(6) NOT NULL,
    MODIFY COLUMN expires_at DATETIME(6) NOT NULL;

-- scheduled_jobs 表
ALTER TABLE scheduled_jobs
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY COLUMN updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);

-- plan_templates 表
ALTER TABLE plan_templates
    MODIFY COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6);

-- 验证：查看 comments 表结构
-- DESCRIBE comments;
-- 应显示：updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
