"""P2 hotfix: drop retry_count + add Task(status, scheduled_date) idx

Revision ID: 829dbe9246d9
Revises: f96919548a94
Create Date: 2026-06-16 07:56:47.973880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829dbe9246d9'
down_revision = 'f96919548a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_column('retry_count')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_status_scheduled', ['status', 'scheduled_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_status_scheduled')

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
